// WARNING: This file is often autogenerated containing specific cluster
// information for a given Kubernetes environment. Update this file and
// add the corresponding *.crt files to this package to customize.

package clusters

import _ "embed"

//go:embed prod.crt
var ProdCA []byte

//go:embed dev.crt
var DevCA []byte

//go:embed inf.crt
var InfCA []byte

// Names contains the keys from the Map for convenience.
var Names = []string{`prod`, `dev`, `inf`}

// Default is the default cluster name to use if none is specified or
// available from the current context.
var Default = `prod`

// Map contains a hard-coded list of cluster information with URLs
// for authentication, the API, and all OIDC information.
var Map = map[string]Cluster{

	`prod`: Cluster{
		Name:          `prod`,
		APIServerURL:  `https://192.168.39.251:8443`,
		OIDCIssuerURL: `https://home.rwx.gg:8443/realms/prod`,
		ClientID:      `minikube-prod`,
		ClientSecret:  `x46aVnFlygaEdHBom1200AZm37ZTWPhe`,
		CA:            ProdCA,
	},

	`dev`: Cluster{
		Name:          `dev`,
		APIServerURL:  `https://192.168.50.73:8443`,
		OIDCIssuerURL: `https://home.rwx.gg:8443/realms/dev`,
		ClientID:      `minikube-dev`,
		ClientSecret:  `12l3IMNHqDvqpp5gm0292g1Hs7SzWgyX`,
		CA:            DevCA,
	},

	`inf`: Cluster{
		Name:          `inf`,
		APIServerURL:  `https://192.168.61.234:8443`,
		OIDCIssuerURL: `https://home.rwx.gg:8443/realms/inf`,
		ClientID:      `minikube-inf`,
		ClientSecret:  `6yw8EH1dVAx9XYKTM2mK2FZZmFhD19Hz`,
		CA:            InfCA,
	},
}
