#!/bin/sh

# This script starts the standard development Keycloak podman container
# that can be configured as an OIDC authentication provider.

podman run \
  --name keycloak \
  --rm \
	-p 8080:8080\
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  quay.io/keycloak/keycloak:latest \
  start-dev
